### ISSUE TITLE
ModuleNotFoundError: No module named 'csci_utils'

### ISSUE THREAD

**Issue by jbosolutions** [DevGlitch/botwizer#2]
ModuleNotFoundError: No module named 'csci_utils'

**Comment by DevGlitch** [comment]
Hi @jbosolutions,

Thanks for reaching out! I no longer maintain this repository, but I can provide some guidance. The error you're seeing (`ModuleNotFoundError: No module named 'csci_utils'`) is because the project relies on the `csci_utils` package, specifically calling the atomic writer functionality from it.

This is a relatively straightforward function that you can find in one of my other repos:  
[csci_utils Atomic Writer](https://github.com/DevGlitch/2020fa-csci-utils-DevGlitch/blob/master/src/csci_utils/io/io.py)

You can either install the `csci_utils` package from the source or directly copy the relevant code into your project. The core part of the file is an atomic writer using `SuffixWriter`, which handles file writing in a way that ensures safety during the write process.

Best of luck!
